- name: Expand seconion managernode Volume Group
  hosts: managernode
  become: true
  become_method: sudo
  vars:
     dev: /dev/sdb
     vg_name: system
     lv_name: nsm
     vg_mapper_name: system-nsm

  tasks:
  - name: create new partition on /dev/sdb
    parted:
      device: "{{dev}}"
      number: 1
      flags: lvm
      label: gpt
      state: present
  - name: Get partition information
    parted:
      device: "{{dev}}"
    register: partinfo
    become: yes
  - debug: var=partinfo.partitions[-1].num
  - debug: var=partinfo.partitions[-1].end
  - name: Probe kernel about partition table changes
    command: partprobe
    become: yes
  - name: "Add the partition /dev/sdb{{partinfo.partitions[-1].num}} to the volume group"
    lvg:
      vg: "{{vg_name}}"
      pvs: "/dev/sda3,{{dev}}{{partinfo.partitions[-1].num}}"
      state: present
    register: lvg_facts
