- name: cleanup repos/rules and other stuff on seconion distributed master node
  hosts: managernode
  become: true
  become_method: sudo

  tasks:
        - name: Pause for 5 minutes for reboot
          pause:
            minutes: 5

        - name: Ensure Bash scripts in /opt/so subdirectories are correct
          shell: "cd /opt/so && find . -name *.sh | while read line;do chmod 754 $line ;done"

        - name: Set airgap mode in salt configuration
          lineinfile:
            dest: /opt/so/saltstack/local/pillar/global.sls
            regexp: '^  airgap: False'
            line: '  airgap: true'
            backrefs: yes

        - name: rerun salt update
          shell: "salt -t 60 \\* state.highstate"

        - name: Create repodata directory
          shell: "mkdir /nsm/repo/repodata"

        - name: Create repo xml files
          shell: "cd /nsm/repo/repodata && createrepo -v /nsm/repo/"

