- name: configure seconion distributed sensor node
  hosts: sensornode
  become: true
  become_method: sudo
  vars_files: vars/secrets.yml

  tasks:
        - name: Pause for 5 minutes for reboot
          pause:
            minutes: 5

        - name: Fix is_airgap variable for unattended offline install on SO 2.3.30, 2.3.61
          lineinfile:
            path: /home/{{so_user}}/SecurityOnion/setup/so-setup
            insertafter: '^automation\=\$2'
            line: 'is_airgap=true'

        - name: Run Security Onion Sensornode Setup
          shell: "sudo /home/{{so_user}}/SecurityOnion/setup/so-setup network distributed-airgap-sensor"
