- name: cleanup repos/rules and other stuff on seconion distributed master node
  hosts: managernode
  become: true
  become_method: sudo

  tasks:
        - name: Pause for 5 minutes for reboot
          pause:
            minutes: 5

        - name: Ensure Bash scripts in /opt/so subdirectories are correct
          shell: "cd /opt/so && find . -name *.sh | while read line;do chmod 754 $line ;done"

        - name: Set airgap mode in salt configuration
          lineinfile:
            dest: /opt/so/saltstack/local/pillar/global.sls
            regexp: '^  airgap: False'
            line: '  airgap: true'
            backrefs: yes

        - name: replace esheap line in seconion manager minion file
          replace:
            path: /opt/so/saltstack/local/pillar/minions/seconion-managernode_manager.sls
            regexp: '^  esheap.*'
            replace: '  esheap: {{esheap}}'

        - name: rerun salt update
          shell: "salt -t 240 \\* state.highstate"
          ignore_errors: yes

        - name: Set DNS server back to original
          lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens192
            regexp: '^DNS1={{old_somgr_dns1}}'
            line: 'DNS1={{new_somgr_dns1}}'
            backrefs: yes
