- name: configure seconion distributed master node
  hosts: managernode
  become: true
  become_method: sudo

  tasks:
        - name: Copy SecOnion Managernode setup configuration file
          copy:
            src: /home/devops/ansible/secOnion-custom/files/distributed-airgap-manager
            dest: /home/user/SecurityOnion/setup/automation/distributed-airgap-manager
            owner: root
            group: user
            mode: 0644

        - name: Add Static IP configuration to ifcfg-ens192
          lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens192
            insertbefore: "^IPV4_FAILURE_FATAL=no"
            line:  "IPADDR="{{manager_ip}}""
        - name: Add Prefix
          lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens192
            insertbefore: "^IPV4_FAILURE_FATAL=no"
            line:  "PREFIX="{{manager_prefix}}""
        - name: Add Gateway
          lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens192
            insertbefore: "^IPV4_FAILURE_FATAL=no"
            line:  "GATEWAY="{{manager_gateway}}""
        - name: Add DNS
          lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens192
            insertbefore: "^IPV4_FAILURE_FATAL=no"
            line:  "DNS1="{{manager_dns1}}"
        - name: Set Boot Protocol to static
          lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens192
            regexp: '^BOOTPROTO=dhcp'
            line: 'BOOTPROTO=static'
            backrefs: yes
        - name: Delete IPV6 lines
          lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens192
            state: absent
            regexp: '^IPV6INIT=yes'
            backrefs: yes
        - name: Delete IPV6 line2
          lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens192
            state: absent
            regexp: '^IPV6_AUTOCONF=yes'
            backrefs: yes
        - name: Delete IPV6 line3
          lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens192
            state: absent
            regexp: '^IPV6_DEFROUTE=yes'
            backrefs: yes
        - name: Delete IPV6 line 4
          lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens192
            state: absent
            regexp: '^IPV6_FAILURE_FATAL=no'
            backrefs: yes
        - name: Delete IPV6 Line 5
          lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens192
            state: absent
            regexp: '^IPV6_ADDR_GEN_MODE=stable-privacy'
            backrefs: yes

        - name: Reboot Security Onion Managernode
          shell: "sudo shutdown -r now"
